### ISSUE TITLE
Investigate S3 Batch for doing batch operation on the backed-up data

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/kafka-backup#20]
S3 Batch could be used to remove objects from the backup, if the retention policy is not good enough

**Comment by antonioiorfino** [comment]
On AWS S3 it is possible to define the retentions by prefix. Using this retention policy could be choose which granularity you want to have (bucket/topic/partition). I think could be enough to use the policy on S3 without any other system to clean the bucket.
