### ISSUE TITLE
Data Retention on backup data

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/kafka-backup#5]
Data retention on the topic should propagate to the backup data. If a segment is deleted from Kafka, then the corresponding data on the backup should be removed as well (after another configurable retention time).

**Comment by antonioiorfino** [comment]
Using the configuration properties of the connector it is possible to set the retention time (in days) about the backup data. Automatically when the connector start will create/update the retention time for the prefix (topic-name/...). In this case we will use the retention of S3 on AWS to remove the old record stored inside the backup
